### ISSUE TITLE
voxel-crunch invocation faulty?

### ISSUE THREAD

**Issue by georgzoeller** [kumavis/voxel-client#4]
Line 70 of index.js invokes voxel-crunch.decode:

   var voxels = crunch.decode(encoded, chunk.length)

However, voxel-crunch 0.2.1 expects the chunk object to be passed rather than the length

  function decode(runs, chunk) {
     var buf_len = chunk.length

leading to decode incorrectly returning an integer containing the runlength rather than the expanded chunk object.

I'm a bit mystified how this ever worked...

**Comment by kumavis** [comment]
hmmm sounds like bit rot -- maybe some shifting dependencies
I haven't taken a look at this module in a little while, so sorry that it didn't work for you.
PRs accepted. Lets me know if you have any other questions and we're on freenode in #voxel.js

**Comment by georgzoeller** [comment]
Just passing in chunk instead of chunk.length fixes it for me. I created a pull request.
